model: vgg16

data:
  path: /Users/sutong20000801/Downloads/xai_bar_lengths
  random_seed: 123
  augmentation:
    rotation_range: 360
    fill_mode: reflect
    horizontal_flip: true
    vertical_flip: true
    width_shift_range: 0.1
    height_shift_range: 0.1
    brightness_range: [0.7, 1.3]
    validation_split: 0.2
  test_split: 0.2
  img_height: 224
  img_width: 224
  img_depth: 3

train:
  epochs: 100
  batch_size: 32
  optimizer:
    lr: 0.001
    decay: 0.0005
  callbacks:
    reduce_lr:
      factor: 0.5
      patience: 5
    early_stopping:
      patience: 10

xai:
  val_test: val
  validation_split: 0.3334
  smoothgrad:
    smooth_samples: 256
    smooth_noise: 0.25
    xinput: false
  barlength_mask:
    corr_threshold: [0.7, 0.75, 0.8, 0.85, 0.9]
    len_threshold: [10, 20, 30, 40, 50]